name: rdf_mapper_annotations
version: 0.2.1-dev
homepage: https://kkalass.github.io/rdf_mapper_annotations/
repository: https://github.com/kkalass/rdf_mapper_annotations
issue_tracker: https://github.com/kkalass/rdf_mapper_annotations/issues
documentation: https://kkalass.github.io/rdf_mapper_annotations/
topics:
  - rdf
  - orm
  - linked-data
  - semantic-web
readme: README.md
changelog: CHANGELOG.md
license: LICENSE
maintainers:
  - "Klas Kala√ü <habbatical@gmail.com>"
description: >
  Dart annotations for declarative RDF graph mapping and code generation.

environment:
  sdk: '^3.6.0'
dependencies:
  rdf_core: ^0.9.3
  rdf_vocabularies: ^0.3.0 
  rdf_mapper: ^0.8.4
  logging: ^1.2.0

dev_dependencies:
  test: ^1.16.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  yaml: ^3.1.2
  path: ^1.8.0
  lints: ^5.1.1
